### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by emilyrose** [mauricesvay/node-wifiscanner#11]
Hey @mauricesvay,

I'm interested in maintaining this module, if you're open to the idea of adding me as a collaborator.

Thanks,
— Emily

**Comment by mauricesvay** [comment]
Hi @emilyrose,

this is the first someone asks me to become maintainer of one my modules.
That sounds like a good idea as I don't have a lot of time to allocate to the project.
I'd be happy to add you as a collaborator.

**Comment by mauricesvay** [comment]
I've add you to the project. Let me know if everything works for you.

**Comment by emilyrose** [comment]
awesome, thanks @mauricesvay!
