### ISSUE TITLE
Publish new version to NPM

### ISSUE THREAD

**Issue by watson** [mauricesvay/node-wifiscanner#16]
Could you please publish a new version of this module to NPM? I'll be happy to help out if you'd like to make me a collaborator.

**Comment by mauricesvay** [comment]
Hi,

I bumped the version to 0.2.1 and published it to npm 
https://www.npmjs.com/package/node-wifiscanner

**Comment by watson** [comment]
@mauricesvay awesome! thanks a lot :)
