### ISSUE TITLE
Child_process error

### ISSUE THREAD

**Issue by Ashish1611** [mauricesvay/node-wifiscanner#21]
when i use it in angular it gives child process error

**Comment by mauricesvay** [comment]
Hi, I'm not familiar with Angular. Can you provide more details on how you use node-wifiscanner with angular? For what's it's worth, node-wifiscanner is meant to be used on the backend, not on the frontend.

**Comment by Ashish1611** [comment]
Ehh,
  in you .ts file write 
  var wifiscanner = require('node-wifi-scanner');
install requirejs librarie
npm install @types/requirejs

after everything it gives child process because node.js library require command line to run in browser it gives error.
